baseURL: https://dom8509.github.io
languageCode: de-DE
title: movement.king.dom
theme: "PaperMod"

params:
  homeInfoParams:
    Title: My Digital Garden 🪴
    Content: Writing, Thoughts and all the other weired insights.

  socialIcons: # optional
    - name: "instagram"
      url: "https://www.instagram.com/movement.king.dom/"
    - name: "github"
      url: "https://github.com/dom8509"
  ShowReadingTime: true
  ListSubpages: false
  disableAnchoredHeadings: false
  author: "Dominik Stamm"
  contact: "movement.king.dom@icloud.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
